### ISSUE TITLE
Train model

### ISSUE THREAD

**Issue by thienbui** [ZJCV/RotNet#1]
How to create dataset to train my model? Thanks

**Comment by zjykzj** [comment]
> How to create dataset to train my model? Thanks

you can refer to [RotNet/rotnet/data/datasets/cifar.py ](https://github.com/ZJCV/RotNet/blob/master/rotnet/data/datasets/cifar.py) to create custom dataset; then register it to [RotNet/rotnet/data/datasets/build.py](https://github.com/ZJCV/RotNet/blob/master/rotnet/data/datasets/build.py); finally use configs/xxx.yaml to train

Or wait for a while and I will create a more convenient way to train custom data.

**Comment by thienbui** [comment]
Thanks, you can upload some samples of dataset ?  Structure of folder data train. Thanks so much!

**Comment by zjykzj** [comment]
> Thanks, you can upload some samples of dataset ? Structure of folder data train. Thanks so much!

Hi, I update the README. You can check how to add custom dataset

**Comment by thienbui** [comment]
Thanks so much!
