### ISSUE TITLE
 No module named 'rotnet'

### ISSUE THREAD

**Issue by dazzafact** [ZJCV/RotNet#10]
Iam getting an error calling tools/train.py
" No module named 'rotnet'"
How to include?

![image](https://user-images.githubusercontent.com/67874406/174460552-2e9e9f33-57ed-43aa-b1a5-ac40228c5235.png)

**Comment by zjykzj** [comment]
> 

You should set project path being root, like README.md said
![2022-06-19 19-51-15屏幕截图](https://user-images.githubusercontent.com/69463217/174479457-ab8bc943-fdaa-4fe1-93ee-6997b991fea3.png)

**Comment by dazzafact** [comment]
Many thanks, i'll try.
iam newby in Python 🥳👈🏼

**Comment by dazzafact** [comment]
Ok, i tried it, but how to pass this Path right?
![image](https://user-images.githubusercontent.com/67874406/174492091-d6afd8ad-5fdd-4f68-98d1-17655ac885eb.png)
![image](https://user-images.githubusercontent.com/67874406/174492139-9997c3d3-0c39-49f4-b76f-50414782a4a8.png)


Many Thanks!

**Comment by zjykzj** [comment]
> 



> Ok, i tried it, but how to pass this Path right? ![image](https://user-images.githubusercontent.com/67874406/174492091-d6afd8ad-5fdd-4f68-98d1-17655ac885eb.png) ![image](https://user-images.githubusercontent.com/67874406/174492139-9997c3d3-0c39-49f4-b76f-50414782a4a8.png)
> 
> Many Thanks!

Not recommend to train in command-line window. You can download WSL to use linux
