### ISSUE TITLE
Pip install zcls -  error

### ISSUE THREAD

**Issue by thienbui** [ZJCV/RotNet#2]
ERROR: Could not find a version that satisfies the requirement zcls==0.3.2
ERROR: No matching distribution found for zcls==0.3.2

Please help!

**Comment by zjykzj** [comment]
> ERROR: Could not find a version that satisfies the requirement zcls==0.3.2
> ERROR: No matching distribution found for zcls==0.3.2
> 
> Please help!

Hi, i add the installation in README. You can check how to install requirements.txt
