### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by bbday** [ZJCV/RotNet#3]
Hi Zjcv, i sent you a couple week ago email to wy163zhuj@163.com, 
let me know if you read it cause i didnt receve any reply

**Comment by zjykzj** [comment]
> Hi Zjcv, i sent you a couple week ago email to [wy163zhuj@163.com](mailto:wy163zhuj@163.com),
> let me know if you read it cause i didnt receve any reply

hi @bbday , I just checked my email and didn't have any related email. You can send it to me again

**Comment by bbday** [comment]
sent, thanks for your reply
