### ISSUE TITLE
What is this algorithm based on?

### ISSUE THREAD

**Issue by yff515** [ZJCV/RotNet#5]
Does this algorithm use a convolutional neural network like the reference?

**Comment by zjykzj** [comment]
> Does this algorithm use a convolutional neural network like the reference?

yes, do it like a classify problem

**Comment by yff515** [comment]
Thank you.So this is a supervised learning algorithm,isn't it?

**Comment by zjykzj** [comment]
> Thank you.So this is a supervised learning algorithm,isn't it?

yes

**Comment by yff515** [comment]
I got it.Thank you.
